# Import BaseModel for data validation
from pydantic import BaseModel

# Used for date-time fields
from datetime import datetime

# Used for list type (comments)
from typing import List


# -------------------- USER SCHEMA --------------------
class UserSchema(BaseModel):
    # Username sent in request body
    username: str


# -------------------- POST SCHEMA --------------------
class PostSchema(BaseModel):
    # Title of the post
    title: str

    # Username of the user who created the post
    username: str

    # Date & time when post is created
    # Usually auto-generated by backend
    created_at: datetime

    # List of comments for the post
    # Example: ["Nice post", "Loved it"]
    comments: List[str]
